name: Create NPM package
on:
  release:
    types: [ created ]
env:
  CI: true
jobs:
  build:
    name: Build NPM package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install
      - name: Build Package
        run: yarn build
      - name: Prepare package.json
        run: node scripts/prepare-package.js
      - name: Change dir to dist
        run: |
          cd dist
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

